export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const COUNTRY_LIST = "COUNTRY_LIST";
export const CLASS_LIST = "CLASS_LIST";
export const BLOOD_GROUP_LIST = "BLOOD_GROUP_LIST";
export const STUDENT_ADD_STATUS = "STUDENT_ADD_STATUS";